export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const ADD_TASK_REQUEST = 'ADD_TASKS_REQUEST'
export const ADD_TASK_SUCCESS = 'ADD_TASKS_SUCCESS'

export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST'
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS'

export const GET_TASK_REQUEST = 'GET_TASK_REQUEST'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'


export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'



